alias gaa="git add -A"
alias gs="git status "
alias gst="git stash "
alias gsta="git stash apply"
alias gstp="git stash pop"
alias gd="git diff "
alias gc="git commit -n " 
alias gp="git pull "
alias gpp="git push "
alias gch="git checkout "
# alias gpo="git pull origin master "
alias gpo="git pull --no-rebase origin master "
alias gpob="git pull --no-rebase origin "
alias gr="git reset --soft HEAD~"
alias grs="git reset --soft HEAD~"
alias grf="git reflog --date=iso"
# alias gcoX="git checkout @{-X}"
gco() {
  git checkout "@{-${1:-1}}"
}
alias gap="git cherry-pick "
alias gcom="git checkout master -- "
alias gcomw="git checkout 'master@{1 week ago}'"
alias gcomm="git checkout 'master@{1 month ago}'"
alias gcomy="git checkout 'master@{1 year ago}'"
